@startuml
class PostIncidenciaDto {
    + Direccion : string <<get>> <<set>>
    + FotoUrl : string? <<get>> <<set>>
    + Titulo : string <<get>> <<set>>
    + Descr : string <<get>> <<set>>
    + IdCategoria : int <<get>> <<set>>
    + IdUsuario : int <<get>> <<set>>
}
@enduml
